# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-16 02:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='m_name',
            new_name='material_name',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='qyt',
            new_name='quantity',
        ),
    ]
