# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-19 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='quantity',
            field=models.CharField(max_length=10),
        ),
    ]
