# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-21 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_auto_20200119_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='material',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
