# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-30 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_auto_20200128_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
