# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-14 08:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Client',
            new_name='client',
        ),
    ]
