# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-20 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
