# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-27 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
