# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-30 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20200129_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateField(),
        ),
    ]
