# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-13 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=100)),
                ('p_image', models.ImageField(upload_to='images/')),
                ('size', models.CharField(max_length=50)),
                ('qyt', models.PositiveIntegerField()),
                ('price', models.FloatField()),
                ('category', models.CharField(choices=[('N', 'without chillie'), ('H', ' hot chillie'), ('M', 'mild chillie'), ('SP', 'siri ya pilau'), ('SM', 'siri ya mchuzi'), ('SC', 'siri ya chai')], max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
