# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-28 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_image', models.ImageField(upload_to='images/')),
                ('product_size', models.CharField(choices=[('10g', '10g'), ('15g', '15g'), ('25g', '25g'), ('35g', '35g')], max_length=50)),
                ('product_qyt', models.PositiveIntegerField()),
                ('product_price', models.FloatField()),
                ('product_category', models.CharField(choices=[('N', 'Without Chillie'), ('H', ' Hot Chillie'), ('M', 'Mild Chillie'), ('SP', 'Siri ya Pilau'), ('SM', 'Siri ya Mchuzi'), ('SC', 'Siri ya Chai')], max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
