# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-23 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_size',
            field=models.CharField(choices=[('10g', '10g'), ('15g', '15g'), ('25g', '25g'), ('35g', '35g')], max_length=50),
        ),
    ]
