# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-15 07:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='product_category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='p_image',
            new_name='product_image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='p_name',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='product_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='qyt',
            new_name='product_qyt',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='size',
            new_name='product_size',
        ),
    ]
