# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-23 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200123_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(choices=[('without chillie', 'without chillie'), ('hot chillie', ' hot chillie'), ('mild chillie', 'mild chillie'), ('siri ya pilau', 'siri ya pilau'), ('siri ya mchuzi', 'siri ya mchuzi'), ('siri ya chai', 'siri ya chai')], max_length=50),
        ),
    ]
