# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-27 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200123_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(choices=[('N', 'Without Chillie'), ('H', ' Hot Chillie'), ('M', 'Mild Chillie'), ('SP', 'Siri ya Pilau'), ('SM', 'Siri ya Mchuzi'), ('SC', 'Siri ya Chai')], max_length=50),
        ),
    ]
